const overViewdata = [
  {
    platform: 'Facebook',
    metric: 'Page Views',
    value: '87',
    percentage: '3%',
    svgIcon: '/images/icon-facebook.svg',
    status: true,
  },
  {
    platform: 'Facebook',
    metric: 'Likes',
    value: '52',
    percentage: '2%',
    svgIcon: '/images/icon-facebook.svg',
    status: false,
  },
  {
    platform: 'Instagram',
    metric: 'Likes',
    value: '5462',
    percentage: '2257%',
    svgIcon: '/images/icon-instagram.svg',
    status: true,
  },
  {
    platform: 'Instagram',
    metric: 'Profile Views',
    value: '52k',
    percentage: '1375%',
    svgIcon: '/images/icon-instagram.svg',
    status: true,
  },
  {
    platform: 'Twitter',
    metric: 'Retweets',
    value: '117',
    percentage: '303%',
    svgIcon: '/images/icon-twitter.svg',
    status: true,
  },
  {
    platform: 'Twitter',
    metric: 'Likes',
    value: '507',
    percentage: '553%',
    svgIcon: '/images/icon-twitter.svg',
    status: true,
  },
  {
    platform: 'YouTube',
    metric: 'Likes',
    value: '107',
    percentage: '19%',
    svgIcon: '/images/icon-youtube.svg',
    status: false,
  },
  {
    platform: 'YouTube',
    metric: 'Total Views',
    value: '1407',
    percentage: '12%',
    svgIcon: '/images/icon-youtube.svg',
    status: false,
  },
]

const profieData = [
  {
    username: '@nathanf',
    followersCount: 1987,
    followersLabel: 'Followers',
    today: '12 Today',
    icon: '/images/icon-facebook.svg',
    plateform: 'facebook',
    status: true,
  },
  {
    username: '@nathanf',
    followersCount: 1044,
    followersLabel: 'Followers',
    today: '99 Today',
    icon: '/images/icon-twitter.svg',
    plateform: 'twitter',
    status: true,
  },
  {
    username: '@realnathanf',
    followersCount: '11k', // Converted 11k to 11000
    followersLabel: 'Followers',
    today: '1099 Today',
    icon: '/images/icon-instagram.svg',
    status: true,
    plateform: 'insta',
  },
  {
    username: 'Nathan F.',
    followersCount: 8239,
    followersLabel: 'Subscribers',
    today: '144 Today',
    icon: '/images/icon-youtube.svg',
    status: false,
    plateform: 'youtube',
  },
]

export { profieData, overViewdata }
